spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed
      properties:
        fetch.min.bytes: 1
        max.poll.interval.ms: 300000
        max.poll.records: 500
