spring:
  kafka:
    consumer:
      group-id: classic-group
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        group.protocol: classic
